/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assessment2;

/**
 *
 * @author GGPC
 */
public class PanelRetire extends javax.swing.JPanel {

    private Model model = new Model();

    /**
     * Creates new form PanelRetire
     */
    public PanelRetire(Model currModel) {
        model = currModel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retireLabel = new javax.swing.JLabel();
        actionRetire = new javax.swing.JButton();
        actionReturn = new javax.swing.JButton();
        banner = new javax.swing.JLabel();
        retireImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 200, 155));

        retireLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        retireLabel.setForeground(new java.awt.Color(255, 255, 255));
        retireLabel.setText("Are you sure you want to retire?");
        retireLabel.setAlignmentX(0.5F);
        retireLabel.setFocusable(false);
        retireLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        actionRetire.setBackground(new java.awt.Color(255, 95, 162));
        actionRetire.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        actionRetire.setForeground(new java.awt.Color(255, 255, 255));
        actionRetire.setText("Retire");
        actionRetire.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        actionRetire.setFocusable(false);
        actionRetire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionRetireActionPerformed(evt);
            }
        });

        actionReturn.setBackground(new java.awt.Color(255, 95, 162));
        actionReturn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        actionReturn.setForeground(new java.awt.Color(255, 255, 255));
        actionReturn.setText("Return");
        actionReturn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        actionReturn.setFocusable(false);
        actionReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionReturnActionPerformed(evt);
            }
        });

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment2/assets/banner.PNG"))); // NOI18N

        retireImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment2/assets/retire.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actionRetire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(retireLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(retireImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(banner)
                .addGap(35, 35, 35)
                .addComponent(retireLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(actionRetire, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(actionReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(retireImg)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    // button to retire and delete your charcter off database
    private void actionRetireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionRetireActionPerformed
        // TODO add your handling code here:
        model.retirePlayer();
        
        System.exit(0);       
    }//GEN-LAST:event_actionRetireActionPerformed

    // button to change your mind 
    private void actionReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionReturnActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
        this.getParent().add(new PanelTown(model));
        this.getParent().revalidate();
        this.getParent().repaint();
    }//GEN-LAST:event_actionReturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionRetire;
    private javax.swing.JButton actionReturn;
    private javax.swing.JLabel banner;
    private javax.swing.JLabel retireImg;
    private javax.swing.JLabel retireLabel;
    // End of variables declaration//GEN-END:variables
}
