/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assessment2;

import java.util.HashMap;

/**
 *
 * @author GGPC
 */
public class PanelTwiceStones extends javax.swing.JPanel {
    
    private Model model = new Model();
   
    /**
     * Creates new form PanelTwiceStones
     */
    public PanelTwiceStones(Model currModel) {
        model = currModel;
        
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerName = new javax.swing.JLabel();
        playerLevel = new javax.swing.JLabel();
        playerTwiceStones = new javax.swing.JLabel();
        playerStrength = new javax.swing.JLabel();
        playerVit = new javax.swing.JLabel();
        playerInt = new javax.swing.JLabel();
        playerInt1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        returnTown = new javax.swing.JButton();
        strButton = new javax.swing.JButton();
        intButton = new javax.swing.JButton();
        vitButton = new javax.swing.JButton();
        charStr = new javax.swing.JLabel();
        charVit = new javax.swing.JLabel();
        charInt = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();
        twiceStonesImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 200, 155));

        playerName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playerName.setForeground(new java.awt.Color(255, 255, 255));
        playerName.setText("Character Name: " + model.player.getCharName());

        playerLevel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playerLevel.setForeground(new java.awt.Color(255, 255, 255));
        playerLevel.setText("Level: " + model.player.getLevel());

        playerTwiceStones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playerTwiceStones.setForeground(new java.awt.Color(255, 255, 255));
        playerTwiceStones.setText("Twice Stones: " +  + model.player.getExp());

        playerStrength.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playerStrength.setForeground(new java.awt.Color(255, 255, 255));
        playerStrength.setText("Strength");

        playerVit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playerVit.setForeground(new java.awt.Color(255, 255, 255));
        playerVit.setText("Vitality");

        playerInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playerInt.setForeground(new java.awt.Color(255, 255, 255));
        playerInt.setText("Intelligence");

        playerInt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playerInt1.setForeground(new java.awt.Color(255, 255, 255));
        playerInt1.setText("Choose attribute to upgrade:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("costs 150 Twice Stones to upgrade");

        returnTown.setBackground(new java.awt.Color(255, 95, 162));
        returnTown.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        returnTown.setForeground(new java.awt.Color(255, 255, 255));
        returnTown.setText("Return to Town");
        returnTown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        returnTown.setFocusable(false);
        returnTown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnTownActionPerformed(evt);
            }
        });

        strButton.setBackground(new java.awt.Color(255, 95, 162));
        strButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        strButton.setForeground(new java.awt.Color(255, 255, 255));
        strButton.setText("+");
        strButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        strButton.setFocusable(false);
        strButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strButtonActionPerformed(evt);
            }
        });

        intButton.setBackground(new java.awt.Color(255, 95, 162));
        intButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        intButton.setForeground(new java.awt.Color(255, 255, 255));
        intButton.setText("+");
        intButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        intButton.setFocusable(false);
        intButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intButtonActionPerformed(evt);
            }
        });

        vitButton.setBackground(new java.awt.Color(255, 95, 162));
        vitButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vitButton.setForeground(new java.awt.Color(255, 255, 255));
        vitButton.setText("+");
        vitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        vitButton.setFocusable(false);
        vitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitButtonActionPerformed(evt);
            }
        });

        charStr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        charStr.setForeground(new java.awt.Color(255, 255, 255));
        charStr.setText(model.playerStats.get("Strength").toString());

        charVit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        charVit.setForeground(new java.awt.Color(255, 255, 255));
        charVit.setText(model.playerStats.get("Vitality").toString());

        charInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        charInt.setForeground(new java.awt.Color(255, 255, 255));
        charInt.setText(model.playerStats.get("Intelligence").toString());

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment2/assets/banner.PNG"))); // NOI18N

        twiceStonesImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment2/assets/twiceStones.png"))); // NOI18N
        twiceStonesImg.setMaximumSize(new java.awt.Dimension(410, 176));
        twiceStonesImg.setMinimumSize(new java.awt.Dimension(410, 176));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(twiceStonesImg, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerTwiceStones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(playerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19))
                            .addComponent(playerLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(returnTown, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(playerStrength, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(playerVit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(playerInt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(charStr)
                                            .addComponent(charVit)
                                            .addComponent(charInt))
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(intButton)
                                            .addComponent(vitButton)
                                            .addComponent(strButton)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(playerInt1)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(banner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTwiceStones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(twiceStonesImg, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(playerInt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(strButton)
                    .addComponent(playerStrength)
                    .addComponent(charStr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(playerVit)
                    .addComponent(vitButton)
                    .addComponent(charVit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(playerInt)
                    .addComponent(intButton)
                    .addComponent(charInt))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(returnTown, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void returnTownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnTownActionPerformed
        // TODO add your handling code here:
        model.returnTown();
        
        this.setVisible(false);
        
        this.getParent().add(new PanelTown(model));
        this.getParent().revalidate();
        this.getParent().repaint();        
    }//GEN-LAST:event_returnTownActionPerformed

    private void strButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strButtonActionPerformed
        // TODO add your handling code here:                                
        charStr.setText(model.increaseAttribute("Strength"));
        
        playerTwiceStones.setText("Twice Stones: " + model.player.getExp());
        playerLevel.setText("Level: " + model.player.getLevel());
    }//GEN-LAST:event_strButtonActionPerformed

    private void vitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitButtonActionPerformed
        // TODO add your handling code here:
        charVit.setText(model.increaseAttribute("Vitality"));
        
        playerTwiceStones.setText("Twice Stones: " + model.player.getExp());
        playerLevel.setText("Level: " + model.player.getLevel());
    }//GEN-LAST:event_vitButtonActionPerformed

    private void intButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intButtonActionPerformed
        // TODO add your handling code here:
        charInt.setText(model.increaseAttribute("Intelligence"));
        
        playerTwiceStones.setText("Twice Stones: " + model.player.getExp());
        playerLevel.setText("Level: " + model.player.getLevel());
    }//GEN-LAST:event_intButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JLabel charInt;
    private javax.swing.JLabel charStr;
    private javax.swing.JLabel charVit;
    private javax.swing.JButton intButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel playerInt;
    private javax.swing.JLabel playerInt1;
    private javax.swing.JLabel playerLevel;
    private javax.swing.JLabel playerName;
    private javax.swing.JLabel playerStrength;
    private javax.swing.JLabel playerTwiceStones;
    private javax.swing.JLabel playerVit;
    private javax.swing.JButton returnTown;
    private javax.swing.JButton strButton;
    private javax.swing.JLabel twiceStonesImg;
    private javax.swing.JButton vitButton;
    // End of variables declaration//GEN-END:variables
}
