/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assessment2;

/**
 *
 * @author GGPC
 */
public class PanelNewGame extends javax.swing.JPanel {

    private Model model = new Model();
    
    /**
     * Creates new form newGamePanel
     */
    public PanelNewGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterNameField = new javax.swing.JTextField();
        contButton = new javax.swing.JButton();
        enterCharNameLabel = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 200, 155));

        enterNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterNameFieldActionPerformed(evt);
            }
        });

        contButton.setBackground(new java.awt.Color(255, 95, 162));
        contButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contButton.setForeground(new java.awt.Color(255, 255, 255));
        contButton.setText("CONTINUE");
        contButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        contButton.setFocusable(false);
        contButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contButtonActionPerformed(evt);
            }
        });

        enterCharNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        enterCharNameLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        enterCharNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterCharNameLabel.setText(" Enter Character Name:");
        enterCharNameLabel.setAlignmentX(0.5F);
        enterCharNameLabel.setFocusCycleRoot(true);
        enterCharNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment2/assets/banner.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterCharNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(enterNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(banner)
                .addGap(65, 65, 65)
                .addComponent(enterCharNameLabel)
                .addGap(18, 18, 18)
                .addComponent(enterNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(contButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enterNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterNameFieldActionPerformed

    private void contButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contButtonActionPerformed
        // TODO add your handling code here:
             
        String charName = enterNameField.getText();
        
        model.newPlayer(charName);
        System.out.println(model.player.getCharName());
                
        this.setVisible(false);
        
        this.getParent().add(new PanelTown(model));
        this.getParent().revalidate();
        this.getParent().repaint();
    }//GEN-LAST:event_contButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JButton contButton;
    private javax.swing.JLabel enterCharNameLabel;
    public javax.swing.JTextField enterNameField;
    // End of variables declaration//GEN-END:variables
}
